local _, ns = ...
local l = ns.I18N;

-- * avoid conflict override
if ns.CONFLICT then return; end
-- ! Replace enabled = false

local DEFAULTS = {
    dbVersion = ns.DB_VERSION or 1403,
    enabled = false, -- FIXME:RFA
    masqueEnabled = false,
    showPlayer = true,
    showParty = true,
    showRaid = true,
    debugMode = false,
    perfMode = false,
    previewEnabled = false,
    previewWidth = 144,
    previewHeight = 72,
    auraFrameStrata = "LOW",
    auraFrameLevel = 35,
    auraAnchorTarget = "HEALTH_BAR",
    showObjectiveCarriers = true,
    objectiveCarrierSize = 20,
    objectiveCarrierAnchor = "TOPRIGHT",
    objectiveCarrierOffsetX = -1,
    objectiveCarrierOffsetY = -1,

    showBuffs = true,
    buffAlpha = 1,
    buffAnchor = "BOTTOMRIGHT",
    buffBorderEnabled = false,
    buffBorderThickness = 1,
    buffDurationAnchor = "CENTER",
    buffDurationColorByTime = true,
    buffDurationHideAboveEnabled = true,
    buffDurationHideAboveThreshold = 60,
    buffDurationFont = "Default",
    buffDurationOutline = "OUTLINE",
    buffDurationScale = 1,
    buffDurationX = 0,
    buffDurationY = 2,
    buffExpiringBorderColor = { r = 1, g = 0.15, b = 0.05, a = 1 },
    buffExpiringBorderColorByTime = false,
    buffExpiringBorderEnabled = false,
    buffExpiringBorderPulsate = false,
    buffExpiringBorderThickness = 2,
    buffExpiringEnabled = false,
    buffExpiringThreshold = 5,
    buffExpiringThresholdMode = "SECONDS",
    buffExpiringTintColor = { r = 1, g = 0.15, b = 0.05, a = 0.35 },
    buffExpiringTintEnabled = false,
    buffGrowth = "LEFT_UP",
    buffHideSwipe = false,
    buffMax = 6,
    buffOffsetX = -2,
    buffOffsetY = 2,
    buffPaddingX = 0,
    buffPaddingY = 0,
    buffShowDuration = true,
    buffSize = 20,
    buffAutoScale = false,
    buffAutoScaleMinSize = 8,
    buffAutoScaleMaxSize = 60,
    buffStackAnchor = "BOTTOMRIGHT",
    buffStackFont = "Default",
    buffStackMinimum = 2,
    buffStackOutline = "OUTLINE",
    buffStackScale = 0.9,
    buffStackX = 2,
    buffStackY = 0,
    buffWrap = 3,

    directBuffShowAll = false,
    directBuffOnlyMine = true,
    directBuffIncludeNameplateOnly = true,
    directBuffHideLong = false,
    directBuffHideLongOnlyInCombat = false,
    directBuffFilterRaidHideInCombat = false,
    directBuffFilterRaid = true,
    directBuffFilterRaidInCombat = true,
    directBuffFilterCancelable = false,
    directBuffFilterNotCancelable = false,
    directBuffFilterImportant = true,
    directBuffFilterImportantScale = 1.1,
    directBuffFilterBigDefensive = true,
    directBuffFilterBigDefensiveScale = 1.3,
    directBuffFilterExternalDefensive = true,
    directBuffFilterExternalDefensiveScale = 1.25,
    directBuffSortOrder = "DEFAULT",
    directBuffSortBigIconsFirst = true,
    directBuffSortReverse = false,

    showDebuffs = true,
    bossDebuffsEnabled = true,
    privateAuraMax = 2,
    privateAuraScale = 1.2,
    privateAuraAnchor = "TOPLEFT",
    privateAuraGrowth = "RIGHT_UP",
    privateAuraWrap = 4,
    privateAuraOffsetX = 0,
    privateAuraOffsetY = 0,
    debuffAlpha = 1,
    debuffAnchor = "BOTTOMLEFT",
    debuffBorderColorBleed = { r = 1, g = 0, b = 0 },
    debuffBorderColorByType = true,
    debuffBorderColorCurse = { r = 0.6, g = 0, b = 1 },
    debuffBorderColorDisease = { r = 0.6, g = 0.4, b = 0 },
    debuffBorderColorMagic = { r = 0.2, g = 0.6, b = 1 },
    debuffBorderColorNone = { r = 0, g = 0, b = 0, a = 1 },
    debuffBorderColorPoison = { r = 0, g = 0.6, b = 0 },
    debuffBorderEnabled = true,
    debuffBorderThickness = 1,
    debuffDurationAnchor = "CENTER",
    debuffDurationColorByTime = true,
    debuffDurationHideAboveEnabled = true,
    debuffDurationHideAboveThreshold = 60,
    debuffDurationFont = "Default",
    debuffDurationOutline = "OUTLINE",
    debuffDurationScale = 0.8,
    debuffDurationX = 0,
    debuffDurationY = 0,
    debuffExpiringBorderColor = { r = 1, g = 0.15, b = 0.05, a = 1 },
    debuffExpiringBorderColorByTime = false,
    debuffExpiringBorderEnabled = false,
    debuffExpiringBorderPulsate = false,
    debuffExpiringBorderThickness = 2,
    debuffExpiringEnabled = false,
    debuffExpiringThreshold = 5,
    debuffExpiringThresholdMode = "SECONDS",
    debuffExpiringTintColor = { r = 1, g = 0.15, b = 0.05, a = 0.35 },
    debuffExpiringTintEnabled = false,
    debuffGrowth = "RIGHT_UP",
    debuffHideSwipe = false,
    debuffMax = 5,
    debuffOffsetX = 2,
    debuffOffsetY = 2,
    debuffPaddingX = 1,
    debuffPaddingY = 1,
    debuffShowDuration = true,
    debuffShowDurationCrowdControlOnly = false,
    debuffSize = 16,
    debuffAutoScale = false,
    debuffAutoScaleMinSize = 8,
    debuffAutoScaleMaxSize = 60,
    debuffStackAnchor = "BOTTOMRIGHT",
    debuffStackFont = "Default",
    debuffStackMinimum = 2,
    debuffStackOutline = "OUTLINE",
    debuffStackScale = 0.9,
    debuffStackX = 2,
    debuffStackY = 0,
    debuffWrap = 3,

    directDebuffShowAll = true,
    directDebuffOnlyMine = false,
    directDebuffIncludeNameplateOnly = true,
    directDebuffFilterRaid = true,
    directDebuffFilterRaidInCombat = true,
    directDebuffFilterCrowdControl = true,
    directDebuffFilterCrowdControlScale = 1.3,
    directDebuffFilterImportant = true,
    directDebuffFilterImportantScale = 1,
    directDebuffDispellableMode = "ALL",
    directDebuffSortOrder = "DEFAULT",
    directDebuffSortBigIconsFirst = true,
    directDebuffSortReverse = false,

    tooltipBuffAnchor = "FRAME",
    tooltipBuffAnchorPos = "BOTTOMRIGHT",
    tooltipBuffDisableInCombat = true,
    tooltipBuffEnabled = true,
    tooltipBuffX = 0,
    tooltipBuffY = -10,
    tooltipDebuffAnchor = "FRAME",
    tooltipDebuffAnchorPos = "BOTTOMLEFT",
    tooltipDebuffDisableInCombat = false,
    tooltipDebuffEnabled = true,
    tooltipDebuffX = 0,
    tooltipDebuffY = -10,

    thresholdExpiringSoon = 5,
    thresholdShortDuration = 60,
    thresholdLongDuration = 300,
    thresholdTransitionOffset = 0.5,
    thresholdColorCritical = { r = 1, g = 0.12, b = 0.04, a = 1 },
    thresholdColorWarning = { r = 1, g = 0.82, b = 0, a = 1 },
    thresholdColorNormal = { r = 1, g = 1, b = 1, a = 1 },
}
ns.DEFAULTS = DEFAULTS
